### ISSUE TITLE
UnhandledPromiseRejection on node-red startup after update to version 2.0.1

### ISSUE THREAD

**Issue by Dani-75** [Looking4Cache/node-red-contrib-remote#20]
25 Feb 00:30:57 - [error] [remote-access:Node-Red Dashboard] requestInstanceSlot: AggregateError
25 Feb 00:30:57 - [red] Uncaught Exception:
25 Feb 00:30:57 - [error] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".
    at throwUnhandledRejectionsMode (node:internal/process/promises:389:7)
    at processPromiseRejections (node:internal/process/promises:470:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:32)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:545:9)
    at processTimers (node:internal/timers:519:7)

**Comment by Looking4Cache** [comment]
I just added more reporting to this function to get closer to that error.

Can you please install the "beta" version 2.0.2 with this command inside your Node-RED folder (normally "~/.node-red")? This is the command for installing it directly from github:
`npm i https://github.com/Looking4Cache/node-red-contrib-remote.git`

After that, the AggregateError should be exploded to all errors hold inside. Can you please append these errors then?

**Comment by Looking4Cache** [comment]
I got some questions:

How much time there is from the line containing "[remote-access:Node-Red Dashboard] Sending config to server:"? If its really a timeout, it should be 30 seconds..

After some seconds the access node should try again to connect. Does the error persist then or does it works on the later tries?

**Comment by Donni1966** [comment]
i have the same error. Reinstall remote, config new - but after setup, reboot node-red i get the same error. Not timeout. it happens directly in the start sprozess.

**Comment by Looking4Cache** [comment]
@Donni1966 @simcmichael Did you both used version 2.0.1 or did you used the test version 2.0.2 from manual install?

> Can you please install the "beta" version 2.0.2 with this command inside your Node-RED folder (normally "~/.node-red")? This is the command for installing it directly from github:
> `npm i https://github.com/Looking4Cache/node-red-contrib-remote.git`

**Comment by Donni1966** [comment]
i use 2.01 - do no manual installing. have to test this - but i run in a docker so the manual install is al little more tricky. 
i will try is next days. 
or can wait for the final version.

**Comment by Looking4Cache** [comment]
@Donni1966 I just released 2.0.2. It will wrap the error so it does not crash Node-RED and does better error reporting.

For me it will be interesting if the Access Node brings an error on startup. And if it works on the next connection try (after some seconds).

**Comment by Donni1966** [comment]
dam  :-) 10 Minutes earlier and i get with the palette update :-D Bit positiv Feedback - is work now aber reboot. For me fine. 

good job thanks a l lot. The ist one of my favourite node-red tool :-)

**Comment by simcmichael** [comment]
Thank you! I still get the error on startup, but it launches now and I can connect. 


`10 Mar 20:05:20 - [info] [remote-access:Home] Server: nodered03.remote-red.com InstanceHash: -----
10 Mar 20:05:22 - [info] [remote-access:Home] Sending config to server: {"name":"Home Security","localip":"192.168.50.22","localport":"1880","localprotocol":"http","baseurl":"/dashboard","timestamp":1741651522024}
10 Mar 20:05:26 - [info] Started flows
10 Mar 20:05:30 - [error] [remote-access:Home] requestInstanceSlot: AggregateError
10 Mar 20:05:30 - [error] [remote-access:Home] AggregateError
10 Mar 20:05:30 - [error] [remote-access:Home] requestInstanceSlot: ETIMEDOUT: AggregateError
    at AxiosError.from (/home/mypi/.node-red/node_modules/axios/dist/node/axios.cjs:857:14)
    at RedirectableRequest.handleRequestError (/home/mypi/.node-red/node_modules/axios/dist/node/axios.cjs:3169:25)
    at RedirectableRequest.emit (node:events:530:35)
    at eventHandlers.<computed> (/home/mypi/.node-red/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:101:11)
    at TLSSocket.socketErrorListener (node:_http_client:504:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/home/mypi/.node-red/node_modules/axios/dist/node/axios.cjs:4258:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
10 Mar 20:05:50 - [info] [remote-access:Home] Sending config to server: {"name":"Home Security","localip":"192.168.50.22","localport":"1880","localprotocol":"http","baseurl":"/dashboard","timestamp":1741651550699}
10 Mar 20:05:52 - [info] [remote-access:Home] Using nodered03.remote-red.com on port 51623
10 Mar 20:05:52 - [info] [remote-access:Home] starting ssh process
10 Mar 20:05:52 - [info] [remote-access:Home] ssh process with pid 2011 started`
